twig:
    file_name_pattern: '*.twig'
    globals:
        cartService: '@App\Service\CartService'
        recaptcha_site_key: '%env(RECAPTCHA_SITE_KEY)%'

when@test:
    twig:
        strict_variables: true
