vich_uploader:
    db_driver: orm

    mappings:
        publication_images:
            uri_prefix: /uploads/publications
            upload_destination: '%kernel.project_dir%/public/uploads/publications'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
